version: '3'

services:
  #rabbit mq
  rabbitmq:
    image: rabbitmq
    networks:
      - akshit  
    ports:
        - 5672:5672
        - 15672:15672
  # #redis
  redis-server: 
    restart: always
    image: redis:6.0-alpine
    networks:
      - akshit  
    volumes:
      - ./server/redis-volume:/data
    ports:
      - '6379:6379'
  #frontend
  frontend:
    build: ./frontend
    container_name: frontend
    hostname: frontend
    ports:
      - '3000:3000'
    networks:
      - akshit  
  # backend
  server:
    build: ./server
    container_name: server
    hostname: server
    environment:
      MONGO_URI: mongodb+srv://username:pass@user-management-cluster.url/user_management?retryWrites=true&w=majority&appName=user-management-cluster
      REDIS_URL: redis://redis-server:6379
      SECRET_JWT: akshitSecretKey
      MA_KEY: somekey
    ports:
      - '5001:5001'
    depends_on:
      - redis-server
      - rabbitmq
    networks:
      - akshit

networks:
  akshit:
    driver: bridge

volumes:
  mongo: {}
